---
- name: Install Go
  ansible.builtin.include_role:
    name: homebrew
    tasks_from: packages.yml
  vars:
    homebrew_formulae: ["{{ dev_tools_go_package }}"]
  when: dev_tools_go_enable | bool
