---
- name: Install Vault
  ansible.builtin.include_role:
    name: homebrew
    tasks_from: packages.yml
  vars:
    homebrew_formulae: ["{{ dev_tools_vault_package }}"]
  when: dev_tools_vault_enable | bool
