---
# hosts/1-system-darwin.nix
aerospace_enable: true
aerospace_config_file: "{{ config_dir }}/dotfiles/config/aerospace/aerospace.toml"
aerospace_scratchpad_file: "{{ config_dir }}/scripts/scratchpad.sh"

brew_enable: true
brew_config_file: "{{ priv_config_dir }}/hosts/{{ inventory_hostname }}/dotfiles/Brewfile"

cli_tools_gnu_enable: true
cli_tools_network_enable: true
cli_tools_network_tmux_config_file: "{{ config_dir }}/dotfiles/tmux.conf"
