---
- name: Track files written by ssh
  ansible.builtin.include_role:
    name: manifest
    tasks_from: track_files.yml
  vars:
    manifest_files: "{{ ssh_managed_files }}"

- name: Configure ssh
  when: ssh_enable | bool
  block:
    - name: Create ~/.ssh
      ansible.builtin.file:
        path: "{{ home_directory }}/.ssh"
        state: directory
        mode: "0700"

    - name: Write ~/.ssh/config
      ansible.builtin.template:
        src: ssh_config.j2
        dest: "{{ home_directory }}/.ssh/config"
        mode: "0600"
