---
- name: Install pdh
  when: pdh_enable | bool
  block:
    - name: Install pipx
      ansible.builtin.include_role:
        name: homebrew
        tasks_from: packages.yml
      vars:
        homebrew_formulae: [pipx]

    - name: Install pdh with pipx
      community.general.pipx:
        name: pdh
        source: "{{ pdh_spec }}"
        state: present
        executable: "{{ homebrew_prefix }}/bin/pipx"
