---
- name: Configure nix utilities
  when: cli_tools_nix_utils_enable | bool
  block:
    - name: Install nix utilities from Homebrew
      ansible.builtin.include_role:
        name: homebrew
        tasks_from: packages.yml
      vars:
        homebrew_formulae: "{{ cli_tools_nix_utils_packages }}"

    - name: Install nixpkgs-only nix utilities
      ansible.builtin.include_role:
        name: nix_profile
      vars:
        nix_profile_packages: "{{ cli_tools_nix_utils_nix_packages }}"
