---
- name: Look for host overrides in the private repository
  ansible.builtin.stat:
    path: "{{ priv_config_vars_file }}"
  register: priv_config_vars_stat

- name: Load host overrides from the private repository
  ansible.builtin.include_vars:
    file: "{{ priv_config_vars_file }}"
  when: priv_config_vars_stat.stat.exists
