---
- name: Track the private configuration checkout
  ansible.builtin.include_role:
    name: manifest
    tasks_from: track_files.yml
  vars:
    manifest_files: "{{ priv_config_managed_files }}"

- name: Fetch the private configuration repository
  ansible.builtin.git:
    repo: "{{ priv_config_repo }}"
    dest: "{{ priv_config_dir }}"
    version: "{{ priv_config_version }}"
    update: "{{ priv_config_update }}"
    accept_newhostkey: true
  when: priv_config_enable | bool

- name: Load host overrides
  ansible.builtin.import_tasks: load_vars.yml
