---
- name: Install Kubernetes clients
  community.general.homebrew:
    name: >-
      {{ (k8s_packages if k8s_enable | bool else [])
         + (k8s_extra_packages if k8s_extra_enable | bool else [])
         + ([k8s_extra_clusterctl_package] if k8s_extra_clusterctl_enable | bool else [])
         + ([k8s_extra_kyverno_package] if k8s_extra_kyverno_enable | bool else [])
         + ([k8s_extra_fluxcd_package] if k8s_extra_fluxcd_enable | bool else [])
         + ([k8s_extra_argocd_package] if k8s_extra_argocd_enable | bool else []) }}
    state: present
  when: >-
    k8s_enable | bool or k8s_extra_enable | bool or k8s_extra_clusterctl_enable | bool
    or k8s_extra_kyverno_enable | bool or k8s_extra_fluxcd_enable | bool or k8s_extra_argocd_enable | bool

- name: Copy krew_list
  ansible.builtin.copy:
    src: "{{ k8s_krew_list_file }}"
    dest: "{{ home_directory }}/krew_list"
    mode: "0644"
  when: k8s_enable | bool
