---
- name: Install Nerd Fonts
  ansible.builtin.include_role:
    name: homebrew
    tasks_from: packages.yml
  vars:
    homebrew_casks: "{{ fonts_nerd_fonts_casks }}"
  when: fonts_nerd_fonts_enable | bool
