---
- name: Install WezTerm
  ansible.builtin.include_role:
    name: homebrew
    tasks_from: packages.yml
  vars:
    homebrew_casks: ["{{ shells_wezterm_cask }}"]
  when: shells_wezterm_enable | bool

- name: Copy wezterm.lua
  ansible.builtin.copy:
    src: "{{ shells_wezterm_config_file }}"
    dest: "{{ home_directory }}/.wezterm.lua"
    mode: "0644"
  when: shells_wezterm_config_file | length > 0
